name: Integrate
 
on:
  pull_request:
    branches: [ main ]

env:
 UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 UNITY_VERSION: 2020.1.15f1
 PROJECT_PATH: Test

jobs:
  test:
    name: Run EditMode and PlayMode Tests ✨
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.2
      
      - name: Cache
        uses: actions/cache@v3.0.4
        with:
         path: ${{ env.projectPath }}/Library
         key: Library-${{ env.projectPath }}
         restore-keys: |
          Library-
      
      - name: Run All Tests
        uses: game-ci/unity-test-runner@v2.0.3
        id: tests
        with:
         unityVersion: ${{ env.UNITY_VERSION }}
         projectPath: ${{ env.PROJECT_PATH }}
         testMode: all
         customParameters: -nographics -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results -coverageOptions generateAdditionalMetrics
         githubToken: ${{ secrets.GITHUB_TOKEN }}
         checkName: Test Results (All)
      
      - name: Upload Results
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
         name: Test Results (All)
         path: ${{ steps.tests.outputs.artifactsPath }}
      
      - name: Upload Codecov Report
        uses: codecov/codecov-action@v3.1.0
        with:
          name: Test Coverage (All)
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.PROJECT_PATH }}/coverage-results/**/*.xml
  linter:
    name: Lint code base 🖥️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Perform Linting
        uses: github/super-linter@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSHARP: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
