name: Update PR

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-labels:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1.1.0
        id: get-latest-tag
        with:
          semver_only: true
  assign:
    name: Auto-Assign
    runs-on: ubuntu-latest
    steps:
      - name: Add Assignee
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
      - name: Create comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            I have automatically assigned ${{ github.actor }} to this pull request. Feel free to edit this if necessary!
